[package]
name = "fuzzing-support"
version = "0.0.0"
edition = "2024"

[dependencies]
bump-scope = { path = "../.." }
arbitrary = { version = "1.3.2", features = ["derive"] }
rangemap = "1.7.0"
zerocopy = { version = "0.8.31", features = ["derive"] }
log = "0.4.29"
